### PR TITLE
Fix a severe bug in the code when the settings change might run even in the PR (NOP) mode. 

### LINKED ISSUE #339: Settings applied from pull request
### What is actually happening
Given a pull request in the `admin` repository with org `settings.yml`, it is possible that settings get applied on the whole organization even though the changes where not yet merged to the main branch.

### What is the expected behavior
Changes from branches/pull requests should never ever be applied before merging to the default branch.

I am reporting this issue since this definitely happened on our side and caused a lot of problems. I was actually expecting that changes get only applied on repositories when the PR is merged to main. I suspect that this happened during a manual trigger of the `re-run` feature of the safe-settings validator.

### Are you using the hosted instance of probot/settings or running your own?
Self-hosted

### If running your own instance, are you using it with github.com or GitHub Enterprise?
GitHub.com

#### Version of probot/settings
2.0.17

### PR DESCRIPTION
**Pull request by decyjphr**
Fix a severe bug in the code when the settings change might run even in the Pull Request (NOP) mode. 

When safe-settings runs in NOP mode, and there are changes to teams settings, it removes the existing teams even when run in the Pull request. This is caused by a bug in the code at https://github.com/github/safe-settings/blob/5dd8e7987f6bf685a44ad857d0c0cc3092cd7002/lib/plugins/teams.js#L75 where 

This fixes #339

### CODE REVIEW

File: lib/plugins/collaborators.js [hunk 1]
```diff
@@ -114,7 +114,7 @@ module.exports = class Collaborators extends Diffable {
     } else {
       if (this.nop) {
         return Promise.resolve([
-          new NopCommand(this.constructor.name, this.repo, this.github.repos.removeCollaborator(
+          new NopCommand(this.constructor.name, this.repo, this.github.repos.removeCollaborator.endpoint(
```
Comment (martinm82) [inline lib/plugins/collaborators.js:117]: Out of curiosity: What is the method `endpoint` doing? I could not find it in the docs: https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/master/docs/repos/removeCollaborator.md.

Comment (decyjphr) [reply lib/plugins/collaborators.js:117]: It is a method in the request that returns the params and the url that would be called by that particular request method. There is an example [here](https://octokit.github.io/rest.js/v18#custom-requests) and the code is [here](https://github.com/octokit/request.js/blob/master/src/with-defaults.ts)

**Review by martinm82 — APPROVED** [review]

File: lib/plugins/collaborators.js (hunk 1 above)
Comment (martinm82) [reply lib/plugins/collaborators.js:117]: Just a dumb idea: How about making `NopCommand` making responsible for calling `.endpoint` in case `endpoint` argument is not null? It would require to provide the endpoint arguments as a separate parameter but at least you would ensure that NopCommand will be the only one calling these methods.

At least I can imagine that this bug might be introduced in the future again.

**Comment by martinm82** [comment]
@decyjphr are you going to merge the fix soon?

File: lib/plugins/collaborators.js (hunk 1 above)
Comment (decyjphr) [reply lib/plugins/collaborators.js:117]: Good idea, I'll make this change separately since it will affect the code broadly and we will need to test it more thoroughly
